[package]
name = "saempler-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Realtime audio engine for Sämpler"

[dependencies]
saempler-model.workspace = true
rtrb.workspace = true

[dev-dependencies]
saempler-model.workspace = true
