[package]
name = "saempler-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Serializable domain model for Sämpler"

[dependencies]
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
